### PR TITLE
Add support for deps.edn

### PR DESCRIPTION
**Pull request by szetobo**

### CODE REVIEW

**Comment by matthewdowney** [comment]
More context, please. Why have a deps.edn and project.clj in the same repository? Is this a common practice? What advantages outweigh the cost of keeping the two syncd?

**Comment by szetobo** [comment]
It just my personal preference to use simpler deps.edn tool bundle with Clojure installation.  They can coexists in a project which can then support both lein & deps.edn at the same time.

**Comment by matthewdowney** [comment]
Oh okay, I think I'm going to leave it as lein-only for now then, and maybe if you want to keep hacking on this project you can have deps.edn in your .gitignore and keep it in your development repo? Fwiw I like deps.edn and have been using it for newer projects, so I'm open to switching in the future.

**Comment by szetobo** [comment]
yup, that's cool, and that's the reason why I separate the changes in this PR from previous one 😄

**Pull request closed without merging**
